Repository AGH-Narzedzia-Informatyczne-2022-2023/PRE-ENGINEERS, pull requests merged in 2022-11, with the labels that each got.

#16 Create przesuwanie tabeli
  przesuwanie tabeli
Labels: enhancement

#22 "Branch martyna mulawa"
  iloczyn skalarny
Labels: nowy pull request

#18 Branch_Lucjan_Bator
  Kodzik_z_C
Labels: documentation
